export const data = {
    uz:{
        header_title:"Muddatli to'lov",
        header_text1:"To'lov xizmatlari, karta va kredit mahsulotlari sohasidagi innovatsion yechimlar.",
        header_text2:"Sodiq mijozlar, maqsadli trafik va qo'shimcha mahsulot aylanmasiga ega bo'ling",
        service_name:"Savdo va xizmat ko'rsatish koxonalari uchun",
        service_text1:"Biz bilan hamkorlik qilish daromadingizni oshiradi va bozordagi raqobatdosh mavqeingizni mustahkamlaydi.",
        service_text2:"Open mijozlarga qimmatroq xaridlar uchun pul beradi",

        service_item1_title:"O'rtacha chekning va foydangizning o’sishi",
        service_item2_title:"Yangi mijozlar va xaridlar sonining oshishi",
        service_item3_title:"Xavfning yo’qligi",
        service_item3_text:"Siz faqat Open kartasi orqali amalga oshirilgan xaridlar uchun komissiya to'laysiz. Biz barcha o'zaro hisob-kitoblarni o'zimiz tashkil qilamiz va soliq masalalari bo'yicha mutaxassislaringizga maslahat beramiz",
        service_item4_title:"Tezkor hisob-kitoblar",
        service_item4_text:"Siz mijozning xaridi uchun to’lovni darhol qabul qilasiz. So’ngra, muddatli to’lov pulini mijoz bankka to’laydi",
        service_item5_title:"Sheriklik marketingi",
        service_item5_text:"Biz reklamalarda o’z mijozlarimiz haqida gapiramiz, dasturimiz va saytimizda ular haqida ma’lumot ko’rsatamiz. Savdolaringizni rag’batlantirish maqsadida turli aksiyalar o’tkazamiz",
        service_item6_title:"Tez va oson ulanish",
        service_item6_text:"Muddatli to’lovga sotishni boshlash uchun siz faqat Open bilan shartnoma tuzishingiz va tranzit bank hisobini ochishingiz kerak (agar hisob mavjud bo'lmasa). Qolganini esa o'zimiz bajaramiz! Muddatli to’lov ertasi kunigayoq ishlashni boshlaydi",
        service_item7_title:"Siz yaxshi kompaniyadasiz",
        service_item7_text:"Open hamkorlar tarmog‘i allaqachon O‘zbekistonning eng yirik hududlarini qamrab olgan. Birinchi bo'lib ulangan hamkorlarda bir qator afzalliklarga bor: qulay sharoitlar va raqobatchilarning ulanishiga rozilik bildirish imkoniyati",
        service_item8_title:"Sotuvchilaringizga ta’lim berish",
        service_item8_text:"Biz sizning savdolaringiz o'sishidan manfaatdormiz. Shuning uchun muntazam ravishda oflayn treninglar va vebinarlar o'tkazamiz. Ularda biz xodimlaringizni Open muddatli to’lovi yordamida o'rtacha xarid chekini oshirish yo’llarini o'rgatamiz. Tadbirlar O‘zbekiston va Rossiyadan kelgan taniqli murabbiylar tomonidan olib borilmoqda",
    
        contained_regions:"Hamkorlar mavjud viloyatlar",
        planned_regions:"Qamrab olish rejalashtirilayotgan viloyatlar",

        partners_header:"Hamkorga aylanish",
        partners_text:"Ushbu shaklni to’ldiring, va biz sizga muddatli to’lov taqdimotini o’tkazamiz va shartnoma tuzishga yordam beramiz",
        partners_input_name:"Tashkilot nomi",
        partners_input_tel:"Telefon raqam",
        partners_btn:"Hamkorga aylanish",

        banks_name:"Banklarga",
        banks_text:"Hamkorlik tarmog’imiz va OpenInstallment texnologiyalari asosida kobrendli muddatli to’lov kartasini atigi bir necha xafta ichida ishga tushirish mumkin. Agarda sizda shaxsiy muddatli to’lov tizimingiz yoki marketplace’ingiz bo’lsa, siz OpenInstallment yordamida o’zingizning xizmatingizni va raqobatchi pozitsiyangizni mustahkamlashingiz mumkin",
        banks_item1_title:"Faol karta mijozlari sonining oshishi",
        banks_item1_text:"Open mijozlarining hisob-kitob hisobvaraqlari sizning bankingizda ochiladi va yuritiladi",
        banks_item2_title:"Mijozlarni jalb qilishning yangi yo’li ",
        banks_item2_text:"Open mijozlarni mustaqil ravishda jalb qiladi va arizani ko'rib chiqish, hisobvaraqasi va kartani ochish uchun ma'lumotlarni bankka o'tkazadi. Bu bank uchun bepul!",
        banks_item3_title:"Yuqori daromad Open kartasi ",
        banks_item3_text:"Orqali to’lov qilinganda bank up-front kommisiyasiga ega bo’ladi, bu esa oz navbatida 34% gacha NPV’ni ta’minlaydi",
        banks_item4_title:"Xavflar pastroq ",
        banks_item4_text:"Open kartasi orqali naqd pul yechish bloklangan. Belgilangan limitni faqat hamkor do’konlarda sarflash mumkin",
        banks_item5_title:"Ijtimoiy javobgarlik va ESG ",
        banks_item5_text:"Open muddatli to’lov tizimi shariat normalariga mos keladi(halol). Mijoz olingan qarz uchun foiz to’lamaydi. Shuningdek, xalqaro qoidalarga muvofiq, muddatli to’lov kartalari ESG-mahsulot sifatida ham ko’rilishi mumkin",
        banks_item6_title:"Shaxsiy muddatli to’lov dasturingizni rivojlantiryapsizmi?",
        banks_item6_text:"Sizga hamkorlar tarmog'ini kengaytirish, daromadlarni oshirish va to'lov kartalarining IT infratuzilmasini optimallashtirish bo'yicha maxsus xizmatlarni taklif qilamiz",

        decision:"Hamkorlikni muhokama qilish",

    },

    ru:{
        header_title:"Рассрочка",
        header_text1:"Инновационные решения в сфере платежных сервисов, карточных и кредитных продуктов.",
        header_text2:"Получайте лояльных клиентов, целевой трафик и дополнительный товарооборот.",
        service_name:"Торговым и сервисным предприятиям",
        service_text1:"Сотрудничество с нами увеличивает вашу прибыль и усиливает конкурентную позицию на рынке.",
        service_text2:"Open дает вашим клиентам деньги на более дорогие покупки",

        service_item1_title:"Рост среднего чека и вашей прибыли",
        service_item2_title:"новые клиенты и рост частоты покупок ",
        service_item3_title:"Отсутствие рисков",
        service_item3_text:"Вы платите комиссию только от фактических покупок по карте Open. Мы сами организуем все взаиморасчеты и проконсультируем ваших специалистов по вопросам налогообложения",
        service_item4_title:"Мгновенные расчеты",
        service_item4_text:"Вы получаете оплату за покупку клиента сразу. А потом сумму рассрочки клиент выплачивает банку",
        service_item5_title:"Совместный маркетинг",
        service_item5_text:"Мы говорим о наших партнерах в рекламе, размещаем информацию о них в приложении и на сайте. И проводим акции для стимулирования ваших продаж",
        service_item6_title:"Быстрое и простое подключение",
        service_item6_text:"Чтобы начать продавать в рассрочку, необходимо только заключить договор с Open и открыть транзитный счет  в банке (если у вас его еще нет). Всё остальное мы сделаем сами! Рассрочка начнет работать уже на следующий день ",
        service_item7_title:"Вы в хорошей компании",
        service_item7_text:"Уже сейчас партнерская сеть Open охватывает крупнейшие регионы Узбекистана. Партнеры, подключившиеся первыми, имеют преимущества: самые выгодные условия и право согласовывать подключение конкурентов",
        service_item8_title:"Обучение ваших продавцов",
        service_item8_text:"Мы заинтересованы в росте ваших продаж. Поэтому мы регулярно проводим офлайн-тренинги и вебинары, где обучаем ваших сотрудников увеличивать средний чек покупок за счет рассрочки Open Мероприятия проводят известные тренеры из Узбекистана и России",

        contained_regions:"Регионы присутствия партнеров",
        planned_regions:"Планируемые регионы охвата",

        partners_header:"Стать партнером",
        partners_text:"Заполните эту форму, и мы проведем для вас презентацию рассрочки и поможем заключить договор ",
        partners_input_name:"Название организации",
        partners_input_tel:"Телефон",
        partners_btn:"Hamkorga aylanish",

        banks_name:"Банкам",
        banks_text:"Запустить кобрендинговую карту рассрочки на базе нашей партнерской сети и технологий OpenInstallment можно всего за несколько недель. Даже если у вас уже есть собственная рассрочка или маркетплейс, вы сможете улучшить свой сервис и конкурентную позицию за счет OpenInstallment.",
        banks_item1_title:"Рост числа активных карточных клиентов ",
        banks_item1_text:"Расчетные счета клиентов Open открываются и ведутся в вашем банке",
        banks_item2_title:"Новый канал привлечения клиентов",
        banks_item2_text:"Open самостоятельно привлекает клиентов и передает банку данные для рассмотрения заявки и открытия счета и карты. Это бесплатно для банка!",
        banks_item3_title:"Высокий доход При оплате картой open",
        banks_item3_text:"Банк получает up-front комиссию, обеспечивающую NPV до 34% годовых",
        banks_item4_title:"Ниже риски",
        banks_item4_text:"Снятие наличных с карты Open заблокировано. Назначенный лимит можно использовать только для покупок в магазинах-партнерах",
        banks_item5_title:"Социальная ответственность и ESG",
        banks_item5_text:"Рассрочка Open соответствует нормам шариата (халяль). Клиент не платит проценты за использование заемных денег. Также согласно международным правилам карты рассрочки могут рассматриваться как ESG-продукты",
        banks_item6_title:"Уже развиваете собственную программу рассрочки? ",
        banks_item6_text:"Предложим вам специальные сервисы по расширению партнерской сети, увеличению дохода и оптимизации ИТ-инфраструктуры карт рассрочки",

        decision:"Обсудить сотрудничество",
    }
}